### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [vinco/frontendvo-blog#23]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by musghost** [comment]
Thanks robot, but we're not interested in share this code.

**Comment by jaromero** [comment]
We should, that was actually the original intent of this.

I actually meant to do this at the start but forgot about it.

**Comment by musghost** [comment]
It's ok. Could you please take over this?

**Comment by jaromero** [comment]
Done. MIT and CC-BY-SA

#24
